name: riverpod_hover_consumer
description: A Flutter widget that provides a hover state for a Consumer Widget.
version: 1.0.0
homepage: 'https://github.com/noskap/riverpod_hover_consumer'

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: RiverpodHoverConsumer
      linux:
        pluginClass: RiverpodHoverConsumer
      web:
        pluginClass: RiverpodHoverConsumer
        fileName: riverpod_hover_consumer.dart.dart
      windows:
        pluginClass: RiverpodHoverConsumer

